### ISSUE TITLE
Does One-Liner Deployment work?

### ISSUE THREAD

**Issue by em3s** [kakao/cuesheet#6]
Even if `-Dcuesheet.install` is given,  this version `0.10.0` submits a job to Yarn.

As I understand, if `-Dcuesheet.install` is defined, no job would be launched. But Cuesheet performs deployment then print a  shell command.

Is it right?

**Comment by jongwook** [comment]
You are right - I inadvertently made the application to run even if `-Dcuesheet.install` is given, while upgrading to `0.10.0`.

I will follow up in #7.
